In [123]:
import numpy as np

In [169]:
import pickle
c=np.load('/home/lkk/code/self-critical.pytorch/data/coco_img_sg/9.npy',encoding="latin1")
c.item().keys()
c.item()

{'rela_matrix': array([[  0.,   1., 417.],
        [  0.,   4., 420.],
        [  0.,   5., 429.],
        [  0.,   7., 410.],
        [  0.,   8., 408.],
        [  0.,   9., 420.],
        [  0.,  15., 429.],
        [  1.,   2., 417.],
        [  1.,   9., 410.],
        [  1.,  15., 429.],
        [  1.,  16., 414.],
        [  2.,   6., 429.],
        [  2.,  15., 429.],
        [  3.,  13., 417.],
        [  4.,   5., 417.],
        [  4.,   7., 417.],
        [  4.,   9., 417.],
        [  4.,  12., 420.],
        [  4.,  22., 420.],
        [  5.,   8., 417.],
        [  5.,  15., 417.],
        [  5.,  22., 420.],
        [  6.,  11., 429.],
        [  6.,  17., 429.],
        [  6.,  19., 417.],
        [  7.,  12., 414.],
        [  7.,  16., 429.],
        [  8.,  22., 429.],
        [  9.,  13., 410.],
        [  9.,  15., 429.],
        [ 11.,  17., 429.],
        [ 11.,  19., 417.],
        [ 12.,  18., 417.],
        [ 12.,  25., 429.],
        [ 13.,  19., 417.],
     

In [155]:
voc = np.load('/home/lkk/code/self-critical.pytorch/data/coco_pred_sg_rela.npy',encoding="latin1")

In [165]:
voc

array({'i2w': {0: 'clock', 1: 'street', 2: 'shade', 3: 'man', 4: 'sneaker', 5: 'headlight', 6: 'car', 7: 'bike', 8: 'sign', 9: 'build', 10: 'sidewalk', 11: 'shirt', 12: 'back', 13: 'glass', 14: 'shoe', 15: 'pant', 16: 'jacket', 17: 'guy', 18: 'van', 19: 'wall', 20: 'tree', 21: 'arm', 22: 'road', 23: 'window', 24: 'backpack', 25: 'street light', 26: 'pole', 27: 'light', 28: 'keyboard', 29: 'monitor', 30: 'drawer', 31: 'mouse', 32: 'desk', 33: 'girl', 34: 'hair', 35: 'chain', 36: 'floor', 37: 'bag', 38: 'strap', 39: 'picture', 40: 'computer', 41: 'photo', 42: 'table', 43: 'handle', 44: 'cabinet', 45: 'curtain', 46: 'chair', 47: 'pillow', 48: 'carpet', 49: 'couch', 50: 'teddy bear', 51: 'frame', 52: 'door', 53: 'cloth', 54: 'seat', 55: 'lamp', 56: 'box', 57: 'book', 58: 'shelf', 59: 'rail', 60: 'paper', 61: 'room', 62: 'clothe', 63: 'apple', 64: 'counter', 65: 'lid', 66: 'fork', 67: 'plate', 68: 'container', 69: 'bowl', 70: 'food', 71: 'bottle', 72: 'cover', 73: 'leg', 74: 'logo', 75: 'la

In [152]:
c.item()['obj_attr'].shape

(26, 7)

In [124]:
c=np.load('/home/lkk/code/self-critical.pytorch/coco_pred_sg_test.npy',encoding="latin1")
len(c.item().keys())

40772

In [126]:
c.item().keys()

dict_keys(['287144', '379412', '89371', '370253', '89377', '221544', '460065', '370259', '286891', '293203', '19396', '5980', '19393', '332249', '155638', '221548', '127478', '155635', '82444', '260521', '304547', '304544', '120122', '235384', '88395', '82993', '489161', '458334', '413926', '413928', '494922', '311171', '279504', '177647', '301345', '322903', '191469', '472593', '195511', '286231', '275', '276', '434126', '36700', '80593', '16703', '88022', '245827', '512876', '512878', '114074', '468641', '545969', '545967', '545966', '153779', '581700', '95796', '9255', '367153', '149145', '46795', '176065', '247464', '21611', '491729', '212828', '461896', '212821', '351341', '353263', '353261', '491726', '124352', '154277', '438869', '438868', '438863', '45443', '20151', '125403', '44790', '458808', '190336', '458806', '387856', '444424', '46867', '387852', '386306', '320500', '82448', '320509', '193820', '479256', '528823', '565032', '415431', '565038', '479259', '479258', '256298'

In [145]:
rr=c.item()['379412']
rr

{'attr_pred': array([[34, 35,  1],
        [34, 98, 28],
        [35,  6, 34],
        [13, 28, 59],
        [35,  4, 23],
        [98, 34, 28],
        [ 4, 28, 10],
        [35,  4, 23],
        [28, 17, 13],
        [28, 98, 13],
        [98, 34, 28],
        [98, 28, 13],
        [27, 10, 50],
        [35,  6, 23],
        [28, 98, 17],
        [35,  6, 34],
        [13, 28, 37],
        [28, 98, 13],
        [13, 28,  0],
        [ 0, 20, 81],
        [17, 28, 98],
        [ 6,  9, 35],
        [35,  1, 27],
        [13, 28, 19],
        [27, 98, 10],
        [98, 27, 28],
        [35,  8,  4],
        [35,  8,  4],
        [ 4, 42,  2],
        [ 4, 42, 83],
        [13,  4, 28],
        [13, 28, 37],
        [98, 28, 34],
        [35,  6, 23],
        [35,  8, 23],
        [28, 98, 13],
        [ 6,  9, 60],
        [35,  6,  4],
        [28, 13, 60],
        [20,  0, 85],
        [19, 17, 37]]), 'obj_pred': array([[111,  99, 290],
        [ 99, 111, 290],
        [  9,  19, 111

In [143]:
s=np.load('/home/lkk/code/self-critical.pytorch/data/testcocobu_att/379412.npz')

In [144]:
s['feat'].shape

(41, 2048)

In [150]:
rr['obj_attr'].shape[0]

KeyError: 'obj_attr'

In [55]:
a=np.load('/home/lkk/code/self-critical.pytorch/data/coco_pred_sg_rela.npy')

In [56]:
b=a.item()

In [57]:
b.keys()

dict_keys(['i2w', 'rela_dict', 'w2i'])

In [58]:
b['i2w']

{0: 'clock',
 1: 'street',
 2: 'shade',
 3: 'man',
 4: 'sneaker',
 5: 'headlight',
 6: 'car',
 7: 'bike',
 8: 'sign',
 9: 'build',
 10: 'sidewalk',
 11: 'shirt',
 12: 'back',
 13: 'glass',
 14: 'shoe',
 15: 'pant',
 16: 'jacket',
 17: 'guy',
 18: 'van',
 19: 'wall',
 20: 'tree',
 21: 'arm',
 22: 'road',
 23: 'window',
 24: 'backpack',
 25: 'street light',
 26: 'pole',
 27: 'light',
 28: 'keyboard',
 29: 'monitor',
 30: 'drawer',
 31: 'mouse',
 32: 'desk',
 33: 'girl',
 34: 'hair',
 35: 'chain',
 36: 'floor',
 37: 'bag',
 38: 'strap',
 39: 'picture',
 40: 'computer',
 41: 'photo',
 42: 'table',
 43: 'handle',
 44: 'cabinet',
 45: 'curtain',
 46: 'chair',
 47: 'pillow',
 48: 'carpet',
 49: 'couch',
 50: 'teddy bear',
 51: 'frame',
 52: 'door',
 53: 'cloth',
 54: 'seat',
 55: 'lamp',
 56: 'box',
 57: 'book',
 58: 'shelf',
 59: 'rail',
 60: 'paper',
 61: 'room',
 62: 'clothe',
 63: 'apple',
 64: 'counter',
 65: 'lid',
 66: 'fork',
 67: 'plate',
 68: 'container',
 69: 'bowl',
 70: 'food',
 

In [59]:
b['w2i']

{'chain': 35,
 'yellow': 325,
 'dish': 84,
 'chair': 46,
 'carpet': 48,
 'tv': 157,
 'stave': 166,
 'young': 342,
 'to': 428,
 'tail': 209,
 'bike': 7,
 'tusk': 293,
 'smile': 343,
 'brown': 314,
 'woman': 77,
 'string': 211,
 'blanket': 118,
 'vase': 144,
 'spoon': 207,
 'cook': 383,
 'wooden': 330,
 'button': 213,
 'cloudy': 367,
 'large': 339,
 'sand': 224,
 'small': 350,
 'guy': 17,
 'rack': 162,
 'bicycle': 132,
 'fence': 106,
 'horn': 277,
 'street': 1,
 'design': 190,
 'rectangular': 362,
 'blue': 324,
 'clock': 0,
 'uniform': 264,
 'above': 446,
 'blue ': 353,
 'bird': 257,
 'thin': 377,
 'leg': 73,
 'men': 140,
 'here': 349,
 'surfer': 303,
 'water': 154,
 'baseball': 402,
 'sink': 159,
 'trunk': 194,
 'along': 416,
 'box': 56,
 'boy': 102,
 'stair': 196,
 'luggage': 156,
 'pillow': 47,
 'apple': 63,
 'strap': 38,
 'snowboard': 297,
 'cloud': 148,
 'eye': 227,
 'sweater': 80,
 'wood': 329,
 'calm': 374,
 'vehicle': 137,
 'looking at': 430,
 'door': 52,
 'under': 425,
 'phone':

In [86]:
b['rela_dict']

{0: 'clock',
 1: 'street',
 2: 'shade',
 3: 'man',
 4: 'sneaker',
 5: 'headlight',
 6: 'car',
 7: 'bike',
 8: 'sign',
 9: 'build',
 10: 'sidewalk',
 11: 'shirt',
 12: 'back',
 13: 'glass',
 14: 'shoe',
 15: 'pant',
 16: 'jacket',
 17: 'guy',
 18: 'van',
 19: 'wall',
 20: 'tree',
 21: 'arm',
 22: 'road',
 23: 'window',
 24: 'backpack',
 25: 'street light',
 26: 'pole',
 27: 'light',
 28: 'keyboard',
 29: 'monitor',
 30: 'drawer',
 31: 'mouse',
 32: 'desk',
 33: 'girl',
 34: 'hair',
 35: 'chain',
 36: 'floor',
 37: 'bag',
 38: 'strap',
 39: 'picture',
 40: 'computer',
 41: 'photo',
 42: 'table',
 43: 'handle',
 44: 'cabinet',
 45: 'curtain',
 46: 'chair',
 47: 'pillow',
 48: 'carpet',
 49: 'couch',
 50: 'teddy bear',
 51: 'frame',
 52: 'door',
 53: 'cloth',
 54: 'seat',
 55: 'lamp',
 56: 'box',
 57: 'book',
 58: 'shelf',
 59: 'rail',
 60: 'paper',
 61: 'room',
 62: 'clothe',
 63: 'apple',
 64: 'counter',
 65: 'lid',
 66: 'fork',
 67: 'plate',
 68: 'container',
 69: 'bowl',
 70: 'food',
 

In [87]:
aa=b['rela_dict'].values()

In [77]:
aa

['clock',
 'street',
 'shade',
 'man',
 'sneaker',
 'headlight',
 'car',
 'bike',
 'sign',
 'build',
 'sidewalk',
 'shirt',
 'back',
 'glass',
 'shoe',
 'pant',
 'jacket',
 'guy',
 'van',
 'wall',
 'tree',
 'arm',
 'road',
 'window',
 'backpack',
 'street light',
 'pole',
 'light',
 'keyboard',
 'monitor',
 'drawer',
 'mouse',
 'desk',
 'girl',
 'hair',
 'chain',
 'floor',
 'bag',
 'strap',
 'picture',
 'computer',
 'photo',
 'table',
 'handle',
 'cabinet',
 'curtain',
 'chair',
 'pillow',
 'carpet',
 'couch',
 'teddy bear',
 'frame',
 'door',
 'cloth',
 'seat',
 'lamp',
 'box',
 'book',
 'shelf',
 'rail',
 'paper',
 'room',
 'clothe',
 'apple',
 'counter',
 'lid',
 'fork',
 'plate',
 'container',
 'bowl',
 'food',
 'bottle',
 'cover',
 'leg',
 'logo',
 'lady',
 'write',
 'woman',
 'wrist',
 'laptop',
 'sweater',
 'sleeve',
 'cup',
 'hand',
 'dish',
 'front',
 'ceiling',
 'tower',
 'wheel',
 'coat',
 'board',
 'screen',
 'pot',
 'flower',
 'plant',
 'key',
 'spot',
 'tray',
 'cord',
 '

In [74]:
bb=list(b['i2w'].values())

In [75]:
bb

['clock',
 'street',
 'shade',
 'man',
 'sneaker',
 'headlight',
 'car',
 'bike',
 'sign',
 'build',
 'sidewalk',
 'shirt',
 'back',
 'glass',
 'shoe',
 'pant',
 'jacket',
 'guy',
 'van',
 'wall',
 'tree',
 'arm',
 'road',
 'window',
 'backpack',
 'street light',
 'pole',
 'light',
 'keyboard',
 'monitor',
 'drawer',
 'mouse',
 'desk',
 'girl',
 'hair',
 'chain',
 'floor',
 'bag',
 'strap',
 'picture',
 'computer',
 'photo',
 'table',
 'handle',
 'cabinet',
 'curtain',
 'chair',
 'pillow',
 'carpet',
 'couch',
 'teddy bear',
 'frame',
 'door',
 'cloth',
 'seat',
 'lamp',
 'box',
 'book',
 'shelf',
 'rail',
 'paper',
 'room',
 'clothe',
 'apple',
 'counter',
 'lid',
 'fork',
 'plate',
 'container',
 'bowl',
 'food',
 'bottle',
 'cover',
 'leg',
 'logo',
 'lady',
 'write',
 'woman',
 'wrist',
 'laptop',
 'sweater',
 'sleeve',
 'cup',
 'hand',
 'dish',
 'front',
 'ceiling',
 'tower',
 'wheel',
 'coat',
 'board',
 'screen',
 'pot',
 'flower',
 'plant',
 'key',
 'spot',
 'tray',
 'cord',
 '

In [72]:
cc=list(b['w2i'].keys())

In [73]:
cc

['chain',
 'yellow',
 'dish',
 'chair',
 'carpet',
 'tv',
 'stave',
 'young',
 'to',
 'tail',
 'bike',
 'tusk',
 'smile',
 'brown',
 'woman',
 'string',
 'blanket',
 'vase',
 'spoon',
 'cook',
 'wooden',
 'button',
 'cloudy',
 'large',
 'sand',
 'small',
 'guy',
 'rack',
 'bicycle',
 'fence',
 'horn',
 'street',
 'design',
 'rectangular',
 'blue',
 'clock',
 'uniform',
 'above',
 'blue ',
 'bird',
 'thin',
 'leg',
 'men',
 'here',
 'surfer',
 'water',
 'baseball',
 'sink',
 'trunk',
 'along',
 'box',
 'boy',
 'stair',
 'luggage',
 'pillow',
 'apple',
 'strap',
 'snowboard',
 'cloud',
 'eye',
 'sweater',
 'wood',
 'calm',
 'vehicle',
 'looking at',
 'door',
 'under',
 'phone',
 'flag',
 'train',
 'stick',
 'hole',
 'hold',
 'fly',
 'word',
 'room',
 'car',
 'cap',
 'next to',
 'roof',
 'cat',
 'donut',
 'tag',
 'can',
 'decorative',
 'grassy',
 'drawer',
 'carrot',
 'airplane',
 'dress',
 'tan',
 'pink',
 'court',
 'sit',
 'on front of',
 'write',
 'lamp',
 'on top of',
 'animal',
 'ele

In [85]:
aa[14:].index('glass')

305

In [83]:
len(set(bb))

448

In [78]:
for one in bb:
    if one not in cc:
        n+=1

In [79]:
n

0

In [67]:
'glass' in cc

True

In [34]:
'chain' in bb

True

In [40]:
d=dict()
for k,v in b['w2i'].items():
    d[v]=k

In [47]:
sorted(d.items(),key=lambda x:x[0])

[(0, 'clock'),
 (1, 'street'),
 (2, 'shade'),
 (3, 'man'),
 (4, 'sneaker'),
 (5, 'headlight'),
 (6, 'car'),
 (7, 'bike'),
 (8, 'sign'),
 (9, 'build'),
 (10, 'sidewalk'),
 (11, 'shirt'),
 (12, 'back'),
 (14, 'shoe'),
 (15, 'pant'),
 (16, 'jacket'),
 (17, 'guy'),
 (18, 'van'),
 (19, 'wall'),
 (20, 'tree'),
 (21, 'arm'),
 (22, 'road'),
 (23, 'window'),
 (24, 'backpack'),
 (25, 'street light'),
 (26, 'pole'),
 (28, 'keyboard'),
 (29, 'monitor'),
 (30, 'drawer'),
 (31, 'mouse'),
 (32, 'desk'),
 (33, 'girl'),
 (34, 'hair'),
 (35, 'chain'),
 (36, 'floor'),
 (37, 'bag'),
 (38, 'strap'),
 (40, 'computer'),
 (41, 'photo'),
 (42, 'table'),
 (43, 'handle'),
 (44, 'cabinet'),
 (45, 'curtain'),
 (46, 'chair'),
 (47, 'pillow'),
 (48, 'carpet'),
 (49, 'couch'),
 (50, 'teddy bear'),
 (52, 'door'),
 (53, 'cloth'),
 (54, 'seat'),
 (55, 'lamp'),
 (56, 'box'),
 (57, 'book'),
 (58, 'shelf'),
 (59, 'rail'),
 (61, 'room'),
 (62, 'clothe'),
 (63, 'apple'),
 (64, 'counter'),
 (65, 'lid'),
 (66, 'fork'),
 (67, '

In [45]:
s=sorted(d.items(),key=lambda x:x[0])

In [48]:
for i,one in enumerate(s):
    if i != one[0]:
        print(i)

13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284

In [109]:
t=[32,102,40,28]


In [110]:
for one in t:
    print(b['rela_dict'][one])

desk
boy
computer
keyboard


In [111]:
r=[408,425,408,410]

In [112]:
for one in r:
    print(b['rela_dict'][one])

on
under
on
ha


In [170]:
a=np.array([[  0.,   3., 417.],
       [  0.,   5., 408.],
       [  0.,  12., 410.],
       [  1.,   2., 409.],
       [  1.,   4., 417.],
       [  3.,   5., 410.],
       [  3.,   8., 410.],
       [  3.,  10., 410.],
       [  5.,  12., 410.],
       [  8.,  14., 410.],
       [  9.,  20., 408.],
       [ 11.,  16., 417.]])


In [201]:
Adj_dis1=np.zeros((21,21))
Adj_dis1.shape

(21, 21)

In [193]:
index=a[:,0:2].astype(np.int)
index

array([[ 0,  3],
       [ 0,  5],
       [ 0, 12],
       [ 1,  2],
       [ 1,  4],
       [ 3,  5],
       [ 3,  8],
       [ 3, 10],
       [ 5, 12],
       [ 8, 14],
       [ 9, 20],
       [11, 16]])

In [203]:
Adj_dis1[index[:, 0], index[:, 1]] = 1
Adj_dis1

array([[0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.,

In [204]:
np.sum(Adj_dis1)

12.0

In [205]:
Adj_dis2=np.zeros((21,21))
Adj_dis2.shape

(21, 21)

In [208]:
Adj_dis1[0,:].nonzero()[0]

array([ 3,  5, 12])

In [ ]:
Adj_dis2[index[:, 0], index[:, 1]] = 1

In [219]:
n1=index[:,0]
n1

array([ 0,  0,  0,  1,  1,  3,  3,  3,  5,  8,  9, 11])

In [220]:
n2=index[:,1]
n2

array([ 3,  5, 12,  2,  4,  5,  8, 10, 12, 14, 20, 16])

In [223]:
mask=np.isin(n2,n1)
mask

array([ True,  True, False, False, False,  True,  True, False, False,
       False, False, False])

In [236]:
set(n2[mask])

{3, 5, 8}

In [231]:
mask2=np.isin(n1,list(set(n2[mask])))
mask2

array([False, False, False, False, False,  True,  True,  True,  True,
        True, False, False])

In [234]:
dis2=index[mask2,:]
dis2

array([[ 3,  5],
       [ 3,  8],
       [ 3, 10],
       [ 5, 12],
       [ 8, 14]])

In [235]:
f

array([3, 3, 3, 5, 8])

In [240]:
d=dict()
d[3]=[]
d[5]=[]
d[8]=[]

In [241]:
for one in set(n2[mask]):
    for item in index:
        if one==item[0]:
            d[one].append(item[1])

In [242]:
d

{3: [5, 8, 10], 5: [12], 8: [14]}

In [243]:
index[mask,:]

array([[0, 3],
       [0, 5],
       [3, 5],
       [3, 8]])

In [244]:
re=[]

In [245]:
for item in index[mask,:]:
    for i in d[item[1]]:
        re.append([item[0],i])

In [246]:
re

[[0, 5], [0, 8], [0, 10], [0, 12], [3, 12], [3, 14]]

In [248]:
re=np.array(re)
re

array([[ 0,  5],
       [ 0,  8],
       [ 0, 10],
       [ 0, 12],
       [ 3, 12],
       [ 3, 14]])

In [251]:
mask3=np.isin(n1,re[:,1])
mask3

array([False, False, False, False, False, False, False, False,  True,
        True, False, False])

In [264]:
mask4=np.isin(re[:,1],n1)
mask4

array([ True,  True, False, False, False, False])

In [267]:
ddd=re[mask4][:,0]

In [253]:
dd=n1[mask3]
dd

array([5, 8])

In [254]:
dd=dict()
dd[5]=[]
dd[8]=[]

In [256]:
for i in dd:
    for item in index:
        if i == item[0]:
            dd[i].append(item[1])

In [257]:
dd

{5: [12], 8: [14]}

In [259]:
index[mask3, :]

array([[ 5, 12],
       [ 8, 14]])

In [ ]:
result=list()

In [269]:
for item in re:
    if item[1] in dd.keys():
        for i in dd[item[1]]:
            result.append([item[0],i])

In [270]:
result

[[0, 12], [0, 14]]

In [ ]:
DataLoader loading json file:  /home/lkk/code/self-critical.pytorch/data/cocotalk.json
vocab size is  9487
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
rela_matrix
array([[  0.,   7., 409.],
       [  0.,  16., 409.],
       [  0.,  18., 409.],
       [  0.,  31., 409.],
       [  1.,   4., 408.],
       [  1.,   7., 425.],
       [  1.,   9., 408.],
       [  1.,  26., 410.],
       [  2.,   3., 413.],
       [  3.,  10., 409.],
       [  3.,  14., 409.],
       [  3.,  16., 408.],
       [  3.,  24., 409.],
       [  4.,   7., 425.],
       [  4.,   9., 408.],
       [  4.,  15., 408.],
       [  7.,  16., 409.],
       [  7.,  31., 409.],
       [  9.,  26., 410.],
       [ 10.,  14., 408.],
       [ 10.,  24., 408.],
       [ 13.,  20., 408.],
       [ 13.,  28., 408.],
       [ 14.,  24., 408.],
       [ 16.,  18., 409.],
       [ 16.,  31., 409.],
       [ 17.,  29., 408.],
       [ 18.,  19., 408.],
       [ 20.,  28., 408.],
       [ 22.,  30., 408.],
       [ 23.,  28., 451.],
       [ 23.,  30., 410.]])


In [271]:
a=np.load('/home/lkk/code/self-critical.pytorch/data/geometry-iou0.2-dist0.5-undirected/1000.npy',encoding='latin1')

In [277]:
a.item()

{'edges': array([[ 0,  1],
        [ 0,  4],
        [ 0,  5],
        [ 0,  9],
        [ 0, 38],
        [ 0, 49],
        [ 1,  2],
        [ 1,  4],
        [ 1,  5],
        [ 1,  6],
        [ 1,  7],
        [ 1,  9],
        [ 1, 11],
        [ 1, 38],
        [ 2,  4],
        [ 2,  7],
        [ 2, 11],
        [ 2, 20],
        [ 2, 30],
        [ 2, 49],
        [ 4,  5],
        [ 4,  6],
        [ 4,  7],
        [ 4,  8],
        [ 4,  9],
        [ 4, 11],
        [ 4, 42],
        [ 5,  7],
        [ 5,  9],
        [ 5, 11],
        [ 5, 14],
        [ 5, 22],
        [ 5, 30],
        [ 5, 42],
        [ 5, 49],
        [ 6, 11],
        [ 6, 23],
        [ 6, 26],
        [ 6, 39],
        [ 7,  9],
        [ 7, 11],
        [ 7, 20],
        [ 7, 24],
        [ 7, 30],
        [ 7, 49],
        [ 8, 21],
        [ 8, 33],
        [ 9, 11],
        [ 9, 14],
        [ 9, 22],
        [ 9, 30],
        [ 9, 32],
        [ 9, 42],
        [ 9, 49],
        [10, 24],
 

In [279]:
a.item()['edges']

array([[ 0,  1],
       [ 0,  4],
       [ 0,  5],
       [ 0,  9],
       [ 0, 38],
       [ 0, 49],
       [ 1,  2],
       [ 1,  4],
       [ 1,  5],
       [ 1,  6],
       [ 1,  7],
       [ 1,  9],
       [ 1, 11],
       [ 1, 38],
       [ 2,  4],
       [ 2,  7],
       [ 2, 11],
       [ 2, 20],
       [ 2, 30],
       [ 2, 49],
       [ 4,  5],
       [ 4,  6],
       [ 4,  7],
       [ 4,  8],
       [ 4,  9],
       [ 4, 11],
       [ 4, 42],
       [ 5,  7],
       [ 5,  9],
       [ 5, 11],
       [ 5, 14],
       [ 5, 22],
       [ 5, 30],
       [ 5, 42],
       [ 5, 49],
       [ 6, 11],
       [ 6, 23],
       [ 6, 26],
       [ 6, 39],
       [ 7,  9],
       [ 7, 11],
       [ 7, 20],
       [ 7, 24],
       [ 7, 30],
       [ 7, 49],
       [ 8, 21],
       [ 8, 33],
       [ 9, 11],
       [ 9, 14],
       [ 9, 22],
       [ 9, 30],
       [ 9, 32],
       [ 9, 42],
       [ 9, 49],
       [10, 24],
       [10, 30],
       [10, 36],
       [10, 37],
       [11, 20

In [278]:
a.item()['feats'].shape

(96, 8)

In [280]:
b=np.load('/home/lkk/code/self-critical.pytorch/data/coco_img_sg/1000.npy',encoding='latin1')

In [286]:
b.item()['rela_matrix']

array([[  0.,   1., 408.],
       [  0.,   4., 441.],
       [  0.,  49., 425.],
       [  1.,   4., 469.],
       [  1.,   5., 420.],
       [  2.,   7., 411.],
       [  2.,  11., 411.],
       [  2.,  20., 409.],
       [  4.,   5., 413.],
       [  5.,   9., 470.],
       [  5.,  49., 409.],
       [  6.,  11., 411.],
       [  6.,  26., 409.],
       [  7.,  11., 411.],
       [  7.,  20., 409.],
       [  7.,  30., 411.],
       [  8.,  21., 409.],
       [  8.,  33., 409.],
       [  9.,  22., 409.],
       [  9.,  49., 409.],
       [ 10.,  36., 409.],
       [ 11.,  20., 409.],
       [ 12.,  18., 408.],
       [ 13.,  14., 408.],
       [ 14.,  22., 417.],
       [ 14.,  24., 411.],
       [ 14.,  37., 411.],
       [ 14.,  49., 409.],
       [ 16.,  32., 408.],
       [ 21.,  33., 409.],
       [ 22.,  32., 409.],
       [ 22.,  49., 409.],
       [ 23.,  26., 408.],
       [ 24.,  30., 411.],
       [ 24.,  37., 414.],
       [ 30.,  37., 417.],
       [ 31.,  42., 413.],
 

In [284]:
b.item()

{'rela_matrix': array([[  0.,   1., 408.],
        [  0.,   4., 441.],
        [  0.,  49., 425.],
        [  1.,   4., 469.],
        [  1.,   5., 420.],
        [  2.,   7., 411.],
        [  2.,  11., 411.],
        [  2.,  20., 409.],
        [  4.,   5., 413.],
        [  5.,   9., 470.],
        [  5.,  49., 409.],
        [  6.,  11., 411.],
        [  6.,  26., 409.],
        [  7.,  11., 411.],
        [  7.,  20., 409.],
        [  7.,  30., 411.],
        [  8.,  21., 409.],
        [  8.,  33., 409.],
        [  9.,  22., 409.],
        [  9.,  49., 409.],
        [ 10.,  36., 409.],
        [ 11.,  20., 409.],
        [ 12.,  18., 408.],
        [ 13.,  14., 408.],
        [ 14.,  22., 417.],
        [ 14.,  24., 411.],
        [ 14.,  37., 411.],
        [ 14.,  49., 409.],
        [ 16.,  32., 408.],
        [ 21.,  33., 409.],
        [ 22.,  32., 409.],
        [ 22.,  49., 409.],
        [ 23.,  26., 408.],
        [ 24.,  30., 411.],
        [ 24.,  37., 414.],
     

In [287]:
import torch.nn as nn

In [289]:
import torch

In [297]:
embed = nn.Sequential(nn.Embedding(10, 5))

In [302]:
a=torch.tensor([[0,1,2,-1],[2,3,4,5]])

In [303]:
a

tensor([[ 0,  1,  2, -1],
        [ 2,  3,  4,  5]])

In [304]:
embed(a)

RuntimeError: index out of range at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:193